default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ndrwkim
  password:

development:
  <<: *default
  database: learnkorean_development

test:
  <<: *default
  database: learnkorean_test